name: Build

on:
  push:
    branches:
      - main

jobs:
  build_application:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Upload Binaries
          path: |
            src-tauri/target/release/**/*.exe
            src-tauri/target/release/**/*.msi
            src-tauri/target/release/**/*.deb
            src-tauri/target/release/**/*.AppImage
            !src-tauri/target/release/deps
            !src-tauri/target/release/build