name: Build

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build_application:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: windows-latest
            args: ""
          - platform: ubuntu-20.04
            args: ""
          - platform: macos-latest
            args: "--target aarch64-apple-darwin"
          - platform: macos-latest
            args: "--target x86_64-apple-darwin"
          - platform: macos-latest
            args: "--target universal-apple-darwin"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Add Rust target
        if: matrix.platform == 'macos-latest' && matrix.args != '--target x86_64-apple-darwin'
        run: rustup target add aarch64-apple-darwin

      - name: Install Dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        run: pnpm install

      - name: Build
        uses: tauri-apps/tauri-action@v0
        with:
          args: ${{ matrix.args }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: toolbox-${{ matrix.platform }}${{ matrix.args }}
          path: |
            src-tauri/**/release/**/*.dmg
            src-tauri/**/release/**/*.app
            src-tauri/**/release/**/*.deb
            src-tauri/**/release/**/*.AppImage
            src-tauri/**/release/**/*.exe
            src-tauri/**/release/**/*.msi
            !src-tauri/**/release/deps
            !src-tauri/**/release/build
